-- *************************************************** --
-- Batch mode on rowstore
-- *************************************************** --
ALTER DATABASE [tpch10g-btree] SET COMPATIBILITY_LEVEL = 150;
GO

USE [tpch10g-btree];
GO

ALTER DATABASE SCOPED CONFIGURATION CLEAR PROCEDURE_CACHE;
GO

-- Row mode due to hint
-- ~ 30 - 40 seconds
SELECT	L_RETURNFLAG,
	L_LINESTATUS,
	SUM(L_QUANTITY)					AS SUM_QTY,
	SUM(L_EXTENDEDPRICE)				AS SUM_BASE_PRICE,
	COUNT(*)					AS COUNT_ORDER
FROM	LINEITEM
WHERE	L_SHIPDATE	<= dateadd(dd, -73, '1998-12-01')
GROUP	BY	L_RETURNFLAG,
		L_LINESTATUS
ORDER	BY	L_RETURNFLAG,
		L_LINESTATUS
OPTION (RECOMPILE, USE HINT('DISALLOW_BATCH_MODE'));

-- Batch mode on row store eligible
-- ~ 10 - 15 seconds
SELECT	L_RETURNFLAG,
	L_LINESTATUS,
	SUM(L_QUANTITY)					AS SUM_QTY,
	SUM(L_EXTENDEDPRICE)				AS SUM_BASE_PRICE,
	COUNT(*)					AS COUNT_ORDER
FROM	LINEITEM
WHERE	L_SHIPDATE	<= dateadd(dd, -73, '1998-12-01')
GROUP	BY	L_RETURNFLAG,
		L_LINESTATUS
ORDER	BY	L_RETURNFLAG,
		L_LINESTATUS
OPTION (RECOMPILE);